device_id = "28372F807B71AAA"
api_key = "2dqq6wyjvhzyb3pqf7sbfozp2hp9h49n"
mac = "28372F807B71"
MODEL = 1
TEST_MODE = false
SSID = "luftdaten.at"
PASSWORD = "clientpassword"
SEND_TO_SENSOR_COMMUNITY = false
CALIBRATION_MODE = false
