ROLLBACK = false
device_id = "DCDA0C7819B9AAA"
api_key = "a6y26gooahslqjf0wzjskeah14klgrs6"
mac = "DCDA0C7819B9"
MODEL = 3
SEND_TO_SENSOR_COMMUNITY = false
TEST_MODE = false
WIFILESS_MODE = true
SSID = "luftdaten.at"
PASSWORD = "clientpassword"
longitude = 0
latitude = 0
height = 0
