ROLLBACK = false
device_id = "DCDA0C7819B9AAA"
api_key = "a6y26gooahslqjf0wzjskeah14klgrs6"
mac = "DCDA0C7819B9"
MODEL = 3
SEND_TO_SENSOR_COMMUNITY = false
TEST_MODE = true
SSID = "cableaerien"
PASSWORD = "gestaltgeber"
latitude = "48.210033"
longitude = "16.363449"
height = "0.0"
