ROLLBACK = false
device_id = "28372F821ADDAAA"
api_key = "ho8evb5hur2udv2fl1487y748ugp42wt"
mac = "28372F821ADD"
MODEL = 1
TEST_MODE = false
SSID = "luftdaten.at"
PASSWORD = "clientpassword"
SEND_TO_SENSOR_COMMUNITY = false
CALIBRATION_MODE = false
