device_id = "A085E3F31851AAA"
api_key = "f6r9zz1n8rqd03zuogocugww5ot93ork"
mac = "A085E3F31851"
MODEL = 2
TEST_MODE = true
SSID = "luftdaten.at"
PASSWORD = "clientpassword"
SEND_TO_SENSOR_COMMUNITY = false
CALIBRATION_MODE = false
