ROLLBACK = false
device_id = "D83BDA43D441AAA"
api_key = "edu6gg5gquco0qegp2o9ax67acrn6mlh"
mac = "D83BDA43D441"
MODEL = 3
TEST_MODE = true
SSID = "luftdaten.at"
PASSWORD = "clientpassword"
SEND_TO_SENSOR_COMMUNITY = false
measurement_interval = 60
battery_save_mode = 0
latitude = "48.2024391"
longitude = "16.343175"
height = "0.0"
