device_id = "D83BDA43D459AAA"
api_key = "qufpbdyyk9p8lnrj2o08upffevf354n7"
mac = "D83BDA43D459"
MODEL = 3
TEST_MODE = false
SSID = "luftdatenEnterprisePEAP"
EAP_IDENTITY = "cisco"
EAP_USERNAME = "cisco"
EAP_PASSWORD = "cisco123!"
SEND_TO_SENSOR_COMMUNITY = false
CALIBRATION_MODE = false
