height = "0.0"
latitude = "48.2024312"
longitude = "16.3431729"
measurement_interval = 30
battery_save_mode = 0
auto_update_mode = 3
device_id = "D83BDA43D035AAA"
api_key = "2je4wtsxd3nw47q0sfca5o1vkbj6skv2"
mac = "D83BDA43D035"
MODEL = 3
TEST_MODE = false
SSID = "luftdaten.at"
PASSWORD = "clientpassword"
SEND_TO_SENSOR_COMMUNITY = false
CALIBRATION_MODE = false
