ROLLBACK = false
device_id = "D83BDA6D37F9AAA"
api_key = "qbj394xpgujjxndopkdg7muhblnvj8yc"
mac = "D83BDA6D37F9"
MODEL = 1
TEST_MODE = false
SSID = "luftdaten.at"
PASSWORD = "clientpassword"
SEND_TO_SENSOR_COMMUNITY = false
CALIBRATION_MODE = false
