model = 3
SSID = ""
PASSWORD = ""
TEST_API_URL = "https://staging.api.luftdaten.at/v1/station/data/"
API_URL = "https://staging.api.luftdaten.at/v1/station/data/"
FIRMWARE_MAJOR = 1
FIRMWARE_MINOR = 3
FIRMWARE_PATCH = 0
PROTOCOL_VERSION = 2
TEST_MODE = true