model=-1
SSID="luftdaten.at"
PASSWORD = "clientpassword"
TEST_API_URL = "https://staging.datahub.luftdaten.at/api/device/status"
API_URL = "https://datahub.luftdaten.at/api/device/status"
FIRMWARE_MAJOR = 1
FIRMWARE_MINOR = 3
FIRMWARE_PATCH = 0
PROTOCOL_VERSION = 2