device_id = "D83BDA6E40A5AAA"
api_key = "5c2l8zbtzu4jgt8nif3zup8ftsydcuey"
mac = "D83BDA6E40A5"
ROLLBACK = false
MODEL = 1
TEST_MODE = false
SSID = "luftdaten.at"
PASSWORD = "clientpassword"
SEND_TO_SENSOR_COMMUNITY = false
